```{r}
# Cài gói nếu cần
library(data.table)

# Đọc dữ liệu
data <- fread("household_power_consumption.txt", na.strings = "?")

# Chuyển cột Date sang Date type
data$Date <- as.Date(data$Date, format="%d/%m/%Y")

# Lọc dữ liệu ngày 2007-02-01 và 2007-02-02
subdata <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")

# Tạo biến datetime để tiện vẽ
subdata$DateTime <- as.POSIXct(paste(subdata$Date, subdata$Time))

```

```{r}
png("plot1.png", width=480, height=480)
hist(subdata$Global_active_power,
     col="red",
     main="Global Active Power",
     xlab="Global Active Power (kilowatts)")
dev.off()

```

```{r}
png("plot2.png", width=480, height=480)
plot(subdata$DateTime, subdata$Global_active_power,
     type="l",
     xlab="",
     ylab="Global Active Power (kilowatts)")
dev.off()


```

```{r}
png("plot3.png", width=480, height=480)
plot(subdata$DateTime, subdata$Sub_metering_1, type="l",
     xlab="", ylab="Energy sub metering")
lines(subdata$DateTime, subdata$Sub_metering_2, col="red")
lines(subdata$DateTime, subdata$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red","blue"),
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()

```

```{r}
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))

# Top-left
plot(subdata$DateTime, subdata$Global_active_power,
     type="l", xlab="", ylab="Global Active Power")

# Top-right
plot(subdata$DateTime, subdata$Voltage,
     type="l", xlab="datetime", ylab="Voltage")

# Bottom-left
plot(subdata$DateTime, subdata$Sub_metering_1, type="l",
     xlab="", ylab="Energy sub metering")
lines(subdata$DateTime, subdata$Sub_metering_2, col="red")
lines(subdata$DateTime, subdata$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red","blue"),
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n")

# Bottom-right
plot(subdata$DateTime, subdata$Global_reactive_power,
     type="l", xlab="datetime", ylab="Global Reactive Power")

dev.off()

```
